fix sphinx autodoc failure, and catch any future ones
Bug: 742115
Change-Id: Icc7c8599c9698bb4e94a9e6eaff266c11a1aab4e

diff --git a/Client/Makefile b/Client/Makefile
--- a/Client/Makefile
+++ b/Client/Makefile
@@ -12,7 +12,12 @@ include ../py_rules.mk
 .PHONY: build
 build: $(_SETUP_PY)
 	env PYTHONPATH=../Common$${PYTHONPATH:+:$$PYTHONPATH} \
-	    python $(SETUP_PY) build
+	    python $(SETUP_PY) build \
+	    | tee build.out
+	@if grep -q ImportError build.out ; then \
+	    echo "ImportErrors in build output, did Sphinx autodoc fail?" ; \
+	    exit 1 ; \
+	fi
 
 install:	py-install
 
diff --git a/Server/Makefile b/Server/Makefile
--- a/Server/Makefile
+++ b/Server/Makefile
@@ -10,7 +10,12 @@ include ../py_rules.mk
 
 build: $(_SETUP_PY)
 	env PYTHONPATH=../Common$${PYTHONPATH:+:$$PYTHONPATH} \
-	    python $(SETUP_PY) build --install-data=/usr/share/
+	    python $(SETUP_PY) build --install-data=/usr/share/ \
+	    | tee build.out
+	@if grep -q ImportError build.out ; then \
+	    echo "ImportErrors in build output, did Sphinx autodoc fail?" ; \
+	    exit 1 ; \
+	fi
 
 install: $(_SETUP_PY)
 	python $(SETUP_PY) install -O1 --skip-build \
